# Generated by Django 4.2.7 on 2023-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0004_alter_useractivity_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchdata',
            name='content_type',
            field=models.CharField(blank=True, choices=[('movie', 'MOVIE'), ('series', 'SERIES'), ('episode', 'EPISODE')], max_length=100, null=True),
        ),
    ]
