# Generated by Django 4.2.7 on 2023-12-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0006_remove_useractivity_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLikeUnlikeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField(unique=True)),
                ('like_count', models.IntegerField(default=0)),
                ('unlike_count', models.IntegerField(default=0)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=50)),
            ],
        ),
    ]
