# Generated by Django 4.2.7 on 2023-12-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0007_contentlikeunlikecount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentlikeunlikecount',
            unique_together={('content_id', 'content_type')},
        ),
    ]
