# Generated by Django 4.2.7 on 2023-12-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0009_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
