# Generated by Django 4.2.7 on 2023-12-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0010_content_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(blank=True, choices=[('movie', 'MOVIE'), ('series', 'SERIES'), ('episode', 'EPISODE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='duration_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='widescreen_thumbnail_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
