# Generated by Django 4.2.7 on 2024-01-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0011_alter_content_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='content_type',
            field=models.CharField(choices=[('movie', 'MOVIE'), ('series', 'SERIES'), ('episode', 'EPISODE')], max_length=100),
        ),
    ]
