# Generated by Django 4.2.7 on 2024-01-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0012_alter_useractivity_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='series_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
