# Generated by Django 4.2.7 on 2024-01-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0013_content_series_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='series_id',
        ),
    ]
