# Generated by Django 4.2.7 on 2024-01-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0015_content_series_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='series_id',
            field=models.IntegerField(default=0),
        ),
    ]
